packages:
  - ".tests"
  - "cloudflare"
  - "cloudflare-d1"
  - "default"
  - "javascript"
  - "minimal"
  - "netlify"
  - "node-custom-server"
  - "node-postgres"
  - "vercel"
  - "unstable_rsc-data-mode-parcel"
  - "unstable_rsc-data-mode-vite"
  - "unstable_rsc-framework-mode"
