packages:
  - ".tests"
  - "cloudflare"
  - "cloudflare-d1"
  - "default"
  - "javascript"
  - "minimal"
  - "netlify"
  - "node-custom-server"
  - "node-postgres"
  - "vercel"
  - "unstable_rsc-parcel"
  - "unstable_rsc-vite"
  - "unstable_rsc-vite-spa"
